<a href="https://colab.research.google.com/github/Vibhor2196/Azure_Deployment/blob/main/Day_2_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
import numpy as np



sentence="Natural Language Processing is so awesome, Isn't it?"


#split sentence into tokens
token_seq=sentence.split() #this method split the string in terms of whitespaces
print(token_seq)

unique_vocab=sorted(set(token_seq))
print(unique_vocab)

# create empty onehot-vector, rows => tokens, columns => unique vocab

num_tokens=len(token_seq)
size_vocab=len(unique_vocab)

print(num_tokens)
print(size_vocab)

#one-hot vector
one_hot_vector=np.zeros(shape=(num_tokens, size_vocab), 
    dtype=int
)



print(one_hot_vector)


#iterate over token sequence build one hot vector
for row,word in enumerate(token_seq):
       col=unique_vocab.index(word)
       one_hot_vector[row,col]=1

# create dataframe with column names
df_onehot = pd.DataFrame(
    data=one_hot_vector,
    columns=unique_vocab
)

print(df_onehot)
       
from collections import Counter
#other way of doing it
tokens=sentence.split()
bow=Counter(tokens)
print(bow)

['Natural', 'Language', 'Processing', 'is', 'so', 'awesome,', "Isn't", 'it?']
["Isn't", 'Language', 'Natural', 'Processing', 'awesome,', 'is', 'it?', 'so']
8
8
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
   Isn't  Language  Natural  Processing  awesome,  is  it?  so
0      0         0        1           0         0   0    0   0
1      0         1        0           0         0   0    0   0
2      0         0        0           1         0   0    0   0
3      0         0        0           0         0   1    0   0
4      0         0        0           0         0   0    0   1
5      0         0        0           0         1   0    0   0
6      1         0        0           0         0   0    0   0
7      0         0        0           0         0   0    1   0
Counter({'Natural': 1, 'Language': 1, 'Processing': 1, 'is': 1, 'so': 1, 'awesome,': 1, "Isn't": 1, 'it?': 1})
